#!perl

# DATE
# VERSION

# NO_PERINCI_CMDLINE_SCRIPT
# FRAGMENT id=shcompgen-hint completer=1 for=mpv

use 5.010001;
use strict;
use warnings;
#use Log::Any '$log';

use App::ShellCompleter::mpv;
use Getopt::Long::Complete; ;# just so it can be detected as Getopt::Long script by Getopt::Long::Util
use ShellCompleter::Util qw(run_shell_completer_for_getopt_long_app);

{
    no warnings 'once';
    run_shell_completer_for_getopt_long_app(
        %App::ShellCompleter::mpv::scargs,
    );
}

# ABSTRACT: Shell completer for mpv
# PODNAME:

=head1 SYNOPSIS

To install, install the CPAN distribution this command comes in with, and then
in your bash (and/or bash startup file):

 complete -C _mpv mpv

or, you can use L<shcompgen> to do that for you automatically.

Now B<mpv> has bash completion:

 % mpv --shu<tab>
